import type { RelayBatonConfig } from "@relay-baton/shared";

export const defaultConfig: RelayBatonConfig = {
  configVersion: 1,
  primaryAgent: "codex",
  fallbackAgent: "claude",
  agents: {
    codex: { command: "codex", args: ["exec", "--sandbox", "workspace-write"] },
    claude: { command: "claude", args: ["--permission-mode", "acceptEdits", "-p"] },
    // v2.3 supported adapters — opt-in via --with / config; not primary defaults.
    opencode: { command: "opencode", args: ["run"] },
    gemini: { command: "gemini", args: ["-p"] },
    aider: { command: "aider", args: ["--message"] },
    cursor: { command: "cursor-agent", args: ["-p"] },
  },
  fallbackPatterns: [
    "usage limit reached",
    "rate limit exceeded",
    "context length exceeded",
    "context limit exceeded",
    "token limit exceeded",
    "quota exceeded",
    "quota limit",
    "insufficient quota",
    "maximum context length",
    "too many requests",
  ],
  commands: { test: "", build: "" },
  authPolicy: {
    mode: "cli-session",
    allowApiKeyEnv: false,
    warnIfApiKeyEnvDetected: true,
    blockedEnvVars: ["OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
  },
  tokenDiet: {
    enabled: true,
    profile: "balanced",
    outputCompression: true,
    profiles: {
      lite: {
        maxHandoffChars: 60000,
        maxDiffChars: 20000,
        maxRepoMapChars: 12000,
        maxLogTailChars: 8000,
        maxStateChars: 8000,
        maxErrorChars: 6000,
        maxPlanChars: 45000,
      },
      balanced: {
        maxHandoffChars: 40000,
        maxDiffChars: 12000,
        maxRepoMapChars: 8000,
        maxLogTailChars: 5000,
        maxStateChars: 6000,
        maxErrorChars: 4000,
        maxPlanChars: 30000,
      },
      caveman: {
        maxHandoffChars: 25000,
        maxDiffChars: 6000,
        maxRepoMapChars: 4000,
        maxLogTailChars: 2500,
        maxStateChars: 3500,
        maxErrorChars: 2500,
        maxPlanChars: 18000,
      },
      ultra: {
        maxHandoffChars: 12000,
        maxDiffChars: 2500,
        maxRepoMapChars: 2000,
        maxLogTailChars: 1000,
        maxStateChars: 1800,
        maxErrorChars: 1000,
        maxPlanChars: 9000,
      },
      off: {
        maxHandoffChars: 200000,
        maxDiffChars: 100000,
        maxRepoMapChars: 50000,
        maxLogTailChars: 50000,
        maxStateChars: 50000,
        maxErrorChars: 50000,
        maxPlanChars: 150000,
      },
    },
  },
  planExecute: {
    defaultPlanner: "claude",
    defaultExecutor: "codex",
    maxPlanChars: 30000,
  },
  contextCompression: {
    enabled: true,
    auto: true,
    threshold: 0.8,
    rotateRawArtifacts: true,
  },
  guardrails: {
    maxSteps: 25,
    maxChangedFiles: 40,
    maxBudgetRatio: 0.9,
    requireConfirmation: true,
  },
};
