import * as fs from "fs";
import * as path from "path";
import type { RelayBatonConfig } from "@relay-baton/shared";
import { SESSION_FILES } from "@relay-baton/shared";
import { SessionManager } from "../session/SessionManager";
import { GitService } from "../git/GitService";
import { ExecutionCheckpoints } from "../plan/ExecutionCheckpoints";

export interface HandoffReportOptions {
  /** Max characters of handoff.md to inline as an excerpt. Default 1200. */
  maxExcerptChars?: number;
}

/**
 * Human-readable markdown status report for PR comments, issue updates, or team
 * chat — assembled from existing artifacts only. Deterministic, read-only, no
 * model calls.
 */
export class HandoffReport {
  constructor(private readonly repoRoot: string, private readonly config?: RelayBatonConfig) {}

  generate(options: HandoffReportOptions = {}): string {
    const maxExcerpt = options.maxExcerptChars ?? 1200;
    const meta = this.config ? new SessionManager(this.repoRoot, this.config).getMeta() : null;
    const git = new GitService(this.repoRoot);
    const summary = git.isGitRepo() ? git.summary(20) : null;
    const checkpoints = new ExecutionCheckpoints(this.repoRoot, this.config).summarize();

    const name = path.basename(this.repoRoot) || "repo";
    const lines: string[] = [];
    lines.push(`# relay-baton handoff report — ${name}`);
    lines.push("");

    lines.push("## Summary");
    lines.push(`- Task: ${meta?.task?.trim() || "(none)"}`);
    lines.push(`- Status: ${meta?.status ?? "(no session)"}`);
    if (meta) lines.push(`- Diet: ${meta.tokenDietProfile} · Agents: ${meta.primaryAgent} -> ${meta.fallbackAgent}`);
    lines.push("");

    lines.push("## Git");
    if (summary) {
      lines.push(`- Branch: ${summary.branch ?? "(detached)"}${summary.head ? ` @ ${summary.head.slice(0, 12)}` : ""}`);
      lines.push(`- Working tree: ${summary.clean ? "clean" : `${summary.changed} changed (${summary.staged} staged, ${summary.unstaged} unstaged, ${summary.untracked} untracked)`}`);
    } else {
      lines.push("- (not a git repository)");
    }
    lines.push("");

    lines.push("## Execution");
    if (checkpoints.total === 0) {
      lines.push("- No checkpoints recorded.");
    } else {
      const r = checkpoints.results;
      lines.push(`- Checkpoints: ${checkpoints.total} (${r.ok} ok, ${r.fail} fail, ${r.pending} pending)`);
      lines.push(`- Last: step ${checkpoints.lastStep} [${checkpoints.lastResult}]${checkpoints.lastCommand ? ` — ${checkpoints.lastCommand}` : ""}`);
    }
    lines.push("");

    const excerpt = this.handoffExcerpt(maxExcerpt);
    if (excerpt) {
      lines.push("## Handoff (excerpt)");
      lines.push("");
      lines.push(excerpt);
      lines.push("");
    }

    lines.push("---");
    lines.push("_Generated by relay-baton from local artifacts only — no model call._");
    return lines.join("\n") + "\n";
  }

  private handoffExcerpt(maxChars: number): string | null {
    let raw = "";
    try { raw = fs.readFileSync(path.join(this.repoRoot, ".ai-session", SESSION_FILES.handoff), "utf8"); } catch { return null; }
    const trimmed = raw.trim();
    if (!trimmed) return null;
    if (trimmed.length <= maxChars) return trimmed;
    return trimmed.slice(0, maxChars) + "\n\n… [handoff truncated in report]";
  }
}
