export class PromptBuilder {
  static claudeContinuation(): string {
    return [
      "You are continuing work from a previous coding agent through relay-baton.",
      "",
      "This is a handoff, not a new task.",
      "",
      "Read these files first:",
      "- AGENTS.md, if it exists",
      "- CLAUDE.md, if it exists",
      "- .ai-session/task.md",
      "- .ai-session/handoff.md",
      "- .ai-session/compact-state.md",
      "- .ai-session/changed-files.md",
      "- .ai-session/repo-map.md",
      "- .ai-session/test-results.md",
      "",
      "Rules:",
      "1. Do not restart from scratch.",
      "2. Trust the current repository state over any assumptions.",
      "3. Inspect git diff before editing.",
      "4. Continue from the \"Next Steps\" section in .ai-session/handoff.md.",
      "5. Preserve existing architecture, naming, and style.",
      "6. Keep changes minimal and targeted.",
      "7. After each meaningful step, update .ai-session/state.md.",
      "8. Before finishing, run relevant tests or explain why tests could not be run.",
      "9. Do not auto-commit unless explicitly asked.",
      "",
      "Token diet rules:",
      "1. Do not read full logs unless necessary.",
      "2. Start with .ai-session/handoff.md and .ai-session/compact-state.md.",
      "3. Read .ai-session/full-diff.patch only if the diff summary is insufficient.",
      "4. Read AGENTS.md and CLAUDE.md by reference, do not ask the user to paste them.",
      "5. Keep your own updates to .ai-session/state.md concise.",
      "6. Avoid re-analyzing unrelated files.",
      "7. Prefer targeted edits over broad refactors.",
      "8. Before asking for more context, inspect the referenced files first.",
      "9. Be concise.",
      "10. Remove filler.",
      "11. Use short direct bullets when reporting progress.",
      "12. Do not repeat the handoff content.",
      "",
      "Immediate task:",
      "Continue the implementation from the handoff file and complete the remaining work.",
    ].join("\n");
  }
}
